spring.application.name=flying.service
server.port=8081
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://flying-postgres:5432/flying_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:flying}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:flying123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
