spring.application.name=backend
server.port=8080
flying.service.url=${FLYING_SERVICE_URL:http://flying-service:8081}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/aterrizar_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aterrizar}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aterrizar123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=500
