CREATE TABLE vuelo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aerolinea VARCHAR(120) NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    origen VARCHAR(100) NOT NULL,
    destino VARCHAR(100) NOT NULL,
    capacidad INTEGER NOT NULL CHECK (capacidad > 0),
    disponibilidad INTEGER NOT NULL CHECK (disponibilidad >= 0 AND disponibilidad <= capacidad)
);

CREATE INDEX idx_vuelo_origen_destino_fecha ON vuelo (origen, destino, fecha);
